name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "lts/*"
    - name: Setup PNPM
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: true
    - run: pnpm test
